#!/usr/bin/env bash
# ============================================================
# generate-secrets.sh
# Generates strong random values for all Velura secrets and
# prints a ready-to-use .env file to stdout.
#
# Usage:
#   bash infra/scripts/generate-secrets.sh > .env
# ============================================================

set -euo pipefail

rand32() { openssl rand -hex 16; }   # 32 hex chars
randpw()  { openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 24; }

echo "# Auto-generated by generate-secrets.sh — $(date -u)"
echo ""
echo "MYSQL_ROOT_PASSWORD=$(randpw)"
echo "MYSQL_HOST=mysql"
echo "MYSQL_PORT=3306"
echo "MYSQL_USER=rental_user"
echo "MYSQL_PASSWORD=$(randpw)"
echo "MYSQL_DATABASE=clothes_rental"
echo ""
echo "JWT_SECRET_KEY=$(rand32)"
echo "AUTH_SERVICE_PORT=5001"
echo "CATALOG_SERVICE_PORT=5002"
echo "RENTAL_SERVICE_PORT=5003"
echo "ADMIN_SERVICE_PORT=5004"
echo ""
echo "AUTH_SERVICE_URL=http://auth-service:5001"
echo ""
echo "FRONTEND_AUTH_URL=http://localhost:5001"
echo "FRONTEND_CATALOG_URL=http://localhost:5002"
echo "FRONTEND_RENTAL_URL=http://localhost:5003"
echo "FRONTEND_ADMIN_URL=http://localhost:5004"
echo ""
echo "FLASK_DEBUG=false"
echo ""
echo "ELASTIC_PASSWORD=$(randpw)"
echo "ELASTICSEARCH_HOSTS=http://clothes_elasticsearch:9200"
echo ""
echo "KIBANA_PASSWORD=$(randpw)"
echo "KIBANA_ENCRYPTION_KEY=$(rand32)"
echo ""
echo "KIBANA_HOST=kibana:5601"
