name: Velura Cloud Platform CI/CD

on:
  push:
    branches: [ main ]

jobs:
  # --- ÉTAPE 1 : VALIDATION ---
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: velura_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run Backend Tests
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/velura_db
          SECRET_KEY: ${{ secrets.BACKEND_SECRET_KEY }}
        run: |
          cd backend
          python test_main.py

  # --- ÉTAPE 2 : LIVRAISON (BUILD ET PUSH) ---
  build-and-push:
    needs: test-backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuration du moteur de build Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion au Registre (Utilise tes secrets GitHub)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build et Push du Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true  # <--- C'EST ICI QUE LE PUSH SE PASSE
          tags: ${{ secrets.DOCKER_USERNAME }}/velura-backend:latest

      # Build et Push du Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true  # <--- C'EST ICI QUE LE PUSH SE PASSE
          tags: ${{ secrets.DOCKER_USERNAME }}/velura-frontend:latest